---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:

    - name: Include Packages
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Set up Environment
      ansible.builtin.include_tasks: tasks/environment.yml

   - name: Set up user
      ansible.builtin.include_tasks: tasks/user.yml

    - name: Set up cron
      ansible.builtin.include_tasks: tasks/cron.yml
