- name: Add ansible-pull cron job
  ansible.builtin.cron:
    name: ansible auto-provision
    user: "{{ user }}"
    hour: "10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/0lzi/workstation-config.git > /dev/null"
