- name: Set oh-my-bash theme
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    search_string: 'OSH_THEME='
    line: OSH_THEME="rr"

- name: Copy Custom aliases
  ansible.builtin.copy:
    src: files/custom.aliases.sh
    dest: /home/{{ user }}/.oh-my-bash/custom/aliases
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  tags: aliases

# Fix to stop duplicate `custom` entries each time it runs
# TODO : Change from shell to replace module
- name: Update OMB .bashrc for custom aliases
  ansible.builtin.shell: sed -i '/  general/ s/$/  \n\  custom/' /home/{{ user }}/.bashrc
  when: not omb_installed.stat.exists
  register: omb_result
  changed_when: omb_result.rc != 0
  ignore_errors: true

- name: Set up personal git folder
  ansible.builtin.file:
    path: /home/{{ user }}/git-personal
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0775'

- name: Set up work git folder
  ansible.builtin.file:
    path: /home/{{ user }}/git
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0775'

- name: check gitconfig
  stat:
    path: /home/{{ user }}/.gitconfig
  register: gitconfig 

- name: check gitconfig work
  stat:
    path: /home/{{ user }}/.gitconfig_work
  register: gitconfigwork 

- name: check ssh config
  stat:
    path: /home/{{ user }}/.ssh/config
  register: sshconfig 

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: files/.gitconfig
    dest: /home/{{ user }}/.gitconfig
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  when: not gitconfig.stat.exists

- name: Copy .gitconfig_work
  ansible.builtin.copy:
    src: files/.gitconfig_work
    dest: /home/{{ user }}/.gitconfig_work
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  when: not gitconfigwork.stat.exists

- name: Copy ~/.ssh/config
  ansible.builtin.copy:
    src: files/config
    dest: /home/{{ user }}/.ssh/config
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  when: not sshconfig.stat.exists

- name: Touch .hushlogin
  ansible.builtin.file:
    dest: /home/{{ user }}.hushlogin
    state: touch
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

# Add wallpaper and change wallpaper
