- name: Install packages
  ansible.builtin.package:
    name: "{{ aptpackages }}"
    state: present
#  with_items: "{{ aptpackages }}" This method was alot slower

- name: Check OhMyBash is installed
  ansible.builtin.stat:
    path: /home/{{ user }}/.oh-my-bash
  register: omb_installed

- name: Install oh-my-bash
  ansible.builtin.shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh) --unattended"
  become: false
  when: not omb_installed.stat.exists
  register: omb_result
  changed_when: omb_result.rc != 0
  ignore_errors: true
  tags: bash

- name: Install VSCODE
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Pip packages
  ansible.builtin.pip:
    name: "{{ pippackages }}"
    state: present
#  with_items: "{{ pippackages }}"

- name: Pipx packages
  ansible.builtin.pip:
    name: "{{ pipxpackages }}"
    state: present
#  with_items: "{{ pipxpackages }}"

- name: Install homebrew 
  community.general.homebrew:
    name: "{{ brewpackages }}"
    state: present
  become: false
#  with_items: "{{ brewpackages }}"

- name: Install snaps
  community.general.snap:
    name: "{{ snappackage }}"
    state: present
#  with_items: "{{ snappackage }}"
