- name: Install packages
  ansible.builtin.package:
    name: "{{ aptpackages }}"
    state: present
#  with_items: "{{ aptpackages }}" This method was alot slower

- name: Install packages desktop
  ansible.builtin.package:
    name: "{{ desktop_packages_apt }}"
    state: present
#  with_items: "{{ aptpackages }}" This method was alot slower
  when: desktop

- name: Check OhMyBash is installed
  ansible.builtin.stat:
    path: /home/{{ user }}/.oh-my-bash
  register: omb_installed

- name: Install oh-my-bash
  ansible.builtin.shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  become: false
  when: not omb_installed.stat.exists
  register: omb_result
  changed_when: omb_result.rc != 0
  ignore_errors: true
  tags: bash

#- name: Install VSCODE
#  ansible.builtin.apt:
#    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
#  when: not ansible_check_mode
  
- name: Pip packages
  ansible.builtin.pip:
    name: "{{ pippackages }}"
    state: present
  when: not ansible_check_mode
#  with_items: "{{ pippackages }}"

- name: Pipx packages
  ansible.builtin.pip:
    name: "{{ pipxpackages }}"
    state: present
  when: not ansible_check_mode
#  with_items: "{{ pipxpackages }}"

- name: Install homebrew
  ansible.builtin.shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: false

- name: Add Homebrew to $PATH
  shell: (echo; echo 'eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"') >> /home/oli/.bashrc" # FIX TO NICER SOLUTION
  become: false
  
- name: Add Homebrew to to PATH
  shell: eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"
  become: false

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ brewpackages }}"
    state: present
  become: false
  when: not ansible_check_mode
#  with_items: "{{ brewpackages }}"

- name: Install snaps
  community.general.snap:
    name: "{{ snappackage }}"
  when: not ansible_check_mode
#  with_items: "{{ snappackage }}"

- name: Install snaps desktop
  community.general.snap:
    name: "{{ desktop_packages_snap }}"
  when: 
    - not ansible_check_mode
    - desktop
#  with_items: "{{ snappackage }}"

- name: Install flatpak
  community.general.flatpak:
    name: "{{ desktop_packages_flatpak }}"
    state: present
  when: 
    - not ansible_check_mode
    - desktop
